name: HPRTMP Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.5'
    - name: Build HPRTMP
      run: swift build
    - name: Test HPRTMP
      run: swift test
